### ISSUE TITLE
Omitted {% load xxx %} statements ?

### ISSUE THREAD

**Issue by perror** [nedbat/django_coverage_plugin#12]
I noticed that all the `{% load xxx %}` statements (such as `{% load i18n %}`) are marked as *uncovered*.

How could we work around and make it covered (and why couldn't we consider all these statements as automatically covered by default ?).

**Comment by nedbat** [comment]
I added a test of `{% load %}` in 2305530, it seems to be covered.  Something more complicated must be going on.  Can you show the file that's having the problem?

**Comment by perror** [comment]
Yes, I confirm that #6 seems to be the same bug.
