### ISSUE TITLE
Don't count the coverage for the entire project if your testing just one app

### ISSUE THREAD

**Issue by epicserve** [nedbat/django_coverage_plugin#14]
So let's say I run something like ``coverage run manage.py test && coverage html && open htmlcov/index.html`` normally to test my entire project and I have ``source = .`` set in my ``.coveragerc`` file. Is there way to make the source or the ``coverage html --include`` automatically adjust if I'm just running tests for one particular Django app that's within my project (i.e. ``coverage run manage.py test apps.foo``).

Right now I'm just manually typing out a command that's getting a little unwieldy and this command is actually sorter now because I'm now using a ``.coveragerc`` file to omit things.

```
coverage run --source="apps/foo" manage.py test apps.foo && coverage html && open htmlcov/index.html
```

I tried making a Makefile rule like ``test_coverage`` that would normally just include all the source in the html report, but then only include the apps source code if I'm testing just one django app within my project, but I gave up because my simple ``ifdef`` statement wasn't working. 

Anyway, is there anyway to include this logic for only showing the source in the html report if the person ran tests for just one app?

**Comment by nedbat** [comment]
I don't see how coverage could do this.  It doesn't know anything about what manage.py is doing, it just runs it.  Perhaps the django test runner could have tighter integration with coverage, and somehow configure it, but I'm not familiar with that code.

**Comment by epicserve** [comment]
That makes sense. I think this existed but the [project](https://bitbucket.org/kmike/django-coverage/) isn't maintained any more and doesn't work with newer versions of Django.
