### ISSUE TITLE
No template reports generated

### ISSUE THREAD

**Issue by nkuttler** [nedbat/django_coverage_plugin#15]
The plugin is active when i run coverage, but the sys_info method never gets called. I verified the file_tracer() calls and my templates don't show up in there either. Any suggestion what to check further would be appreciated.

Django==1.8.3
coverage==4.0a6
django-coverage-plugin==0.5

**Comment by nedbat** [comment]
Can you show how you are running your tests, and coverage, and include the results of the coverage report?  Also, a link to the repo with the project in it (if possible) would be great.  Can you try the latest version of the plugin (which would require using an unpackaged version of coverage.py)?

**Comment by gergelypolonkai** [comment]
Same here with:

    Django==1.8.4
    coverage==4.0b2
    django-coverage-plugin==1.0b2

My `.coveragerc` file:

    [run]
    plugins =
        django_coverage_plugin

    [report]
    omit =
        demand-venv/*
        /app/*
        demand/wsgi.py

I run coverage like:

    coverage run --source="demand,builds,accounts,api,process" manage.py test

**Comment by nedbat** [comment]
@gergelypolonkai Can you provide me with a link to your repo?

**Comment by gergelypolonkai** [comment]
Sorry, it's a company-only repo. I can do some tests on a private repo this evening (CEST) with the same versions.

**Comment by codingjoe** [comment]
Same here in a private repo. Plugin is installed but it doesn't show any template coverage.

**Comment by nedbat** [comment]
Can you add ``--debug=sys,config`` to your ``coverage run`` command, and show the output?  Also, perhaps the output of ``coverage debug data`` ?

**Comment by codingjoe** [comment]
Did you ever test it with pytest-cov?

**Comment by nedbat** [comment]
I have not tested it with pytest-cov, is that what you are using?

**Comment by codingjoe** [comment]
I tried both. But I'd prefer to use pytest-cov because of it's subprocessing support.

**Comment by gergelypolonkai** [comment]
With `--debug=sys,config` I get a bunch of this message:

    builds/templates/builds/create.html   ImproperlyConfigured: Requested setting FILE_CHARSET, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

If I add this to my `settings.py`, it doesn’t help.

**Comment by nedbat** [comment]
@codingjoe @gergelypolonkai Have you set DJANGO_SETTINGS_MODULE as an environment variable?  If you could post the results of the --debug switch, it might help me help you.

**Comment by gergelypolonkai** [comment]
There you go.

    -- config ----------------------------------------------------
     attempted_config_files: /local/scratch/polesz/dmnd/.coveragerc
                     branch: False
                concurrency: None
               config_files: /local/scratch/polesz/dmnd/.coveragerc
                cover_pylib: False
                  data_file: .coverage
                      debug: sys
                             config
               exclude_list: (?i)#\s*pragma[:\s]?\s*no\s*cover
                  extra_css: None
                 fail_under: 0
                   html_dir: htmlcov
                 html_title: Coverage report
              ignore_errors: False
                    include: None
                       note: None
                       omit: dmnd-venv/*
                             /app/*
                             dmnd/wsgi.py
                   parallel: False
        partial_always_list: while (True|1|False|0):
                             if (True|1|False|0):
               partial_list: (?i)#\s*pragma[:\s]?\s*no\s*branch
                      paths: {}
             plugin_options: {}
                    plugins: django_coverage_plugin
                  precision: 0
               show_missing: False
               skip_covered: False
                     source: dmnd
                             builds
                             accounts
                             api
                             process
                      timid: False
                 xml_output: coverage.xml
          xml_package_depth: 99
    -- sys -------------------------------------------------------
                  version: 4.0b2
                 coverage: /local/scratch/polesz/dmnd/dmnd-venv/lib/python2.7/site-packages/coverage/__init__.pyc
               cover_dirs: /local/scratch/polesz/dmnd/dmnd-venv/lib/python2.7/site-packages/coverage
               pylib_dirs: /afs/sunrise.ericsson.se/se/app/vbuild/SLED11-x86_64/python/2.7.1/lib/python2.7
                   tracer: CTracer
     plugins.file_tracers: django_coverage_plugin.DjangoTemplatePlugin
             config_files: /local/scratch/polesz/dmnd/.coveragerc
             configs_read: /local/scratch/polesz/dmnd/.coveragerc
                data_path: /local/scratch/polesz/dmnd/.coverage
                   python: 2.7.1 (r271:86832, Apr 14 2014, 13:39:29) [GCC 4.8.2]
                 platform: Linux-3.0.101-0.29-default-x86_64-with-SuSE-11-x86_64
           implementation: CPython
               executable: /local/scratch/polesz/dmnd/dmnd-venv/bin/python
                      cwd: /local/scratch/polesz/dmnd
                     path: 
                           /app/vbuild/SLED11-x86_64/python/2.7-addons-virtualenv/lib/python2.7/site-packages/setuptools-3.3-py2.7.egg
                           /app/vbuild/SLED11-x86_64/python/2.7-addons-virtualenv/lib/python2.7/site-packages/pip-1.2.1-py2.7.egg
                           /app/vbuild/SLED11-x86_64/python/2.7-addons-virtualenv/lib/python2.7/site-packages/virtualenv-1.11.4-py2.7.egg
                           /app/vbuild/SLED11-x86_64/python/3.4-addons-git-review/lib/python3.4/site-packages/setuptools-7.0-py3.4.egg
                           /app/vbuild/SLED11-x86_64/python/3.4-addons-git-review/lib/python3.4/site-packages/pip-1.5.6-py3.4.egg
                           /app/vbuild/SLED11-x86_64/python/3.4-addons-git-review/lib/python3.4/site-packages/requests-2.5.0-py3.4.egg
                           /app/vbuild/SLED11-x86_64/python/3.4-addons-git-review/lib/python3.4/site-packages/argparse-1.2.2-py3.4.egg
                           /local/scratch/polesz/dmnd/dmnd-venv/src/django-jux
                           /app/vbuild/SLED11-x86_64/python/2.7-addons-virtualenv/lib/python2.7/site-packages
                           /app/vbuild/SLED11-x86_64/python/3.4-addons-git-review/lib/python3.4/site-packages
                           /app/vbuild/SLED11-x86_64/pygtk/2.24.0-2.7/lib/python2.7/site-packages/gtk-2.0
                           /app/vbuild/SLED11-x86_64/pygtk/2.24.0-2.7/lib/python2.7/site-packages
                           /local/scratch/polesz/dmnd/dmnd-venv/lib/python27.zip
                           /local/scratch/polesz/dmnd/dmnd-venv/lib/python2.7
                           /local/scratch/polesz/dmnd/dmnd-venv/lib/python2.7/plat-linux2
                           /local/scratch/polesz/dmnd/dmnd-venv/lib/python2.7/lib-tk
                           /local/scratch/polesz/dmnd/dmnd-venv/lib/python2.7/lib-old
                           /local/scratch/polesz/dmnd/dmnd-venv/lib/python2.7/lib-dynload
                           /app/vbuild/SLED11-x86_64/python/2.7.1/lib/python2.7
                           /app/vbuild/SLED11-x86_64/python/2.7.1/lib/python2.7/plat-linux2
                           /app/vbuild/SLED11-x86_64/python/2.7.1/lib/python2.7/lib-tk
                           /local/scratch/polesz/dmnd/dmnd-venv/lib/python2.7/site-packages
              environment: PYTHONPATH = /app/vbuild/SLED11-x86_64/python/2.7-addons-virtualenv/lib/python2.7/site-packages:/app/vbuild/SLE
    D11-x86_64/python/3.4-addons-git-review/lib/python3.4/site-packages:/app/vbuild/SLED11-x86_64/pygtk/2.24.0-2.7/lib/python2.7/site-pack
    ages/gtk-2.0:/app/vbuild/SLED11-x86_64/pygtk/2.24.0-2.7/lib/python2.7/site-packages
                           PYTHONSTARTUP = /etc/pythonstart
             command_line: /local/scratch/polesz/dmnd/dmnd-venv/bin/coverage run --rcfile=/local/scratch/polesz/dmnd/.coveragerc -
    -source=dmnd,builds,accounts,api,process --debug=sys,config manage.py test
             source_match: /local/scratch/polesz/dmnd/dmnd
                           /local/scratch/polesz/dmnd/builds
                           /local/scratch/polesz/dmnd/accounts
                           /local/scratch/polesz/dmnd/api
                           /local/scratch/polesz/dmnd/process
        source_pkgs_match: -none-
            include_match: -none-
               omit_match: /local/scratch/polesz/dmnd/dmnd-venv/*
                           /afs/sunrise.ericsson.se/se/app/*
                           /local/scratch/polesz/dmnd/dmnd/wsgi.py
              cover_match: -none-
              pylib_match: -none-
    -- sys: django_coverage_plugin.DjangoTemplatePlugin ----------
     django_template_dir: /local/scratch/polesz/dmnd/dmnd-venv/lib/python2.7/site-packages/django/template
             environment: DJANGO_SETTINGS_MODULE = dmnd.settings_juno
    -- end -------------------------------------------------------

**Comment by codingjoe** [comment]
@nedbat I use django-configurations, so no.

**Comment by nedbat** [comment]
OK, I think I know what is going on here.  In Django <= 1.7, you need to have TEMPLATE_DEBUG=True defined in your settings.py.  In Django 1.8, you need to be using the new TEMPLATES setting, and set OPTIONS['debug'] = True.
Can you try this and confirm for me that it works or does not work?

**Comment by gergelypolonkai** [comment]
I already had that during the previous tests. Here are the relevant lines from my `settings.py`:

```python
DEBUG = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': DEBUG,
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'builds.helper.warn_title',
            ],
        },
    },
]
```

**Comment by nedbat** [comment]
@gergelypolonkai I'm a little unsure about how the DEBUG setting interacts here, since the test runner sets it to False.  Do you mind changing this to `'debug': True` to see if it changes the behavior?

**Comment by gergelypolonkai** [comment]
I think that is evaluated before starting the test runner. Anyways, I will try it as soon as I gut in the office tomorrow (~0900 CEST).

**Comment by gergelypolonkai** [comment]
It seems I have forgot to save my comment here…

I had the same issu with `debug` explicitly set to `True`. However, patching `get_template` in `plugin.py` to initialize Django settings before using it did the trick:

    if not settings.configured:
        settings.configure()

After this, I got template coverage data.

**Comment by codingjoe** [comment]
@gergelypolonkai when `get_template` method? I can't find it. I'd like to try it myself.

**Comment by gergelypolonkai** [comment]
Sorry, method name suffers from copy-paste error… it is `read_template_source` actually.

**Comment by gergelypolonkai** [comment]
I have opened #16 for this.

**Comment by nedbat** [comment]
I've merged #16, can people try it and tell me if it's better?

**Comment by nedbat** [comment]
I've pushed 1.1 with this change: https://pypi.python.org/pypi/django_coverage_plugin/1.1

**Comment by gergelypolonkai** [comment]
I have just downloaded it and it works like charm. Thanks!
