### ISSUE TITLE
Add a note that `TEMPLATE_DEBUG` must be enabled.

### ISSUE THREAD

**Issue by charettes** [nedbat/django_coverage_plugin#17]
I had to read the source to figure out it was required. Fixing the TODO would also be nice.

**Comment by nedbat** [comment]
Even better, I'd like to add an automated warning message if TEMPLATE_DEBUG is not set.

**Comment by audreyr** [comment]
Just fyi, as of Django 1.8, TEMPLATE_DEBUG is deprecated: https://docs.djangoproject.com/en/1.8/ref/settings/#template-debug

**Comment by charettes** [comment]
I has been replaced by the `'debug'` option in the `OPTIONS` of a `DjangoTemplates` backend.

**Comment by nedbat** [comment]
This is handled in 99ba553

**Comment by charettes** [comment]
Thanks Ned!

**Comment by jonashaag** [comment]
Will you cut a a release with this fix soon? I spent almost an hour debugging this.

**Comment by nedbat** [comment]
Version 1.2 is on PyPI now, with this fix.  Sorry for the delay :)

**Comment by jonashaag** [comment]
Thank you!
