### ISSUE TITLE
No template lines covered

### ISSUE THREAD

**Issue by degustaf** [nedbat/django_coverage_plugin#24]
I have multiple tests that render a response, but I am showing 0 coverage in my templates.

The repo is https://github.com/degustaf/symmetrical-eureka
And the coverage report can be seen at https://travis-ci.org/degustaf/symmetrical-eureka/jobs/128951675

Possibly related, I have a base template for displaying a common header for all pages on the site, which does not show at all in the coverage report.

**Comment by knyghty** [comment]
I'm having the same issue - did you ever figure this out?

**Comment by jambonrose** [comment]
I just cloned [`symmetrical-eureka`](https://github.com/degustaf/symmetrical-eureka) and ran the tests locally with Python 3.5, Django 1.11, Coverage 4.5.1 with C extension, and django_coverage_plugin v1.6rc1. I'm seeing the templates being listed as covered, so I'm guessing you sorted the issue out, and am therefore closing the issue.

If either of you are still having problems with this package, please re-open this issue or open a new issue. Thanks!
