### ISSUE TITLE
How to access Django settings?

### ISSUE THREAD

**Issue by nedbat** [nedbat/django_coverage_plugin#3]
When using other coverage commands (like `coverage html`), the Django settings may not be set properly.  For example, these commands:

```
coverage run manage.py test ; coverage html
```

manage.py will set the settings properly, but `coverage html` won't know where they are.
Should we require the user to set the DJANGO_SETTINGS_MODULE? Should we make it so the settings aren't required?

**Comment by jessamynsmith** [comment]
If I simply run in my usual virtualenv environment, I get errors like the following:
```
$ coverage report
Coverage.py warning: Setting timid=True to support plugins.
Name                                                                  Stmts   Miss Branch BrPart  Cover
-------------------------------------------------------------------------------------------------------
eggtimer/libs/email_sender.py                                             8      5      2      0    30%
eggtimer/templates/base.html   ImportError: Could not import settings 'eggtimer.settings.development' (Is it on sys.path? Is there an import error in the settings file?): No module named 'eggtimer'
```
I can work around this by setting PYTHONPATH:
```
$ export PYTHONPATH=.
(eggtimer3)~/Development/eggtimer$ coverage report
Coverage.py warning: Setting timid=True to support plugins.
Name                                                                  Stmts   Miss Branch BrPart  Cover
-------------------------------------------------------------------------------------------------------
eggtimer/libs/email_sender.py                                             8      5      2      0    30%
eggtimer/templates/base.html                                             39     23      0      0    41%
```
It also works, without PYTHONPATH, if I invoke coverage via python:
```
$ python -m coverage report
Coverage.py warning: Setting timid=True to support plugins.
Name                                                                  Stmts   Miss Branch BrPart  Cover
-------------------------------------------------------------------------------------------------------
eggtimer/libs/email_sender.py                                             8      5      2      0    30%
eggtimer/templates/base.html                                             39     23      0      0    41%
```

**Comment by perror** [comment]
In my humble opinion, it would be much more easy to use if a default `DJANGO_SETTINGS_MODULE` is selected at first (e.g. the one from the current project).

**Comment by nedbat** [comment]
@perror I'm not sure what you mean.  What is the default DJANGO_SETTINGS_MODULE?

**Comment by perror** [comment]
@nedbat In fact, I need to set the `DJANGO_SETTINGS_MODULES` to `myapp.settings` to make the plugin work. It would be more convenient if a default value could be set to it (I have no idea how to achieve this though...). But, anyway, it is not really important because it works once it is configured, so it is not really an issue.

**Comment by gergelypolonkai** [comment]
Doesn’t calling `django.setup()` do this for you?

**Comment by nedbat** [comment]
@gergelypolonkai I'll admit to being a little confused.  I need to do some more tests on real Django projects.  Anyone who can provide data points, I am grateful!

**Comment by gergelypolonkai** [comment]
I take this back; `DJANGO_SETTINGS_MODULE` must be set for this. However, `wsgi.py` and thus the `manage.py runserver` command sets it to a sane default, and in a gunicorn/Apache/whatever environment you use the former one.

Still, `django.setup()`, or at least `settings.configure()` should be called befora accessing the config (see #16 which solves somewhat the same issue).

**Comment by PamelaM** [comment]
+1 for setting DJANGO_SETTINGS_MODULE.  Our situation is way more complicated since we have three projects that *intimately* share the same code tree.  Each project has it's own settings, so there are some templates in project A that aren't accessed in project L and visa-versa.  

It would be miraculous if we could specify a list of settings to find all templates, but we're happy with just getting full template coverage on all of A and any L templates that are also in A's directories

**Comment by sergei-maertens** [comment]
One thing I noticed is that for `coveralls` the `PYTHONPATH` trick is required, while settings `DJANGO_SETTINGS_MODULE` is enough for `codecov`. For Travis, I just export both env vars before submitting the coverage to Coveralls/Codecov

**Comment by jambonrose** [comment]
Closing this issue: setting `DJANGO_SETTINGS_MODULE` is documented in the Read Me.
