### ISSUE TITLE
Possible to remove Django from install_requires?

### ISSUE THREAD

**Issue by beaugunderson** [nedbat/django_coverage_plugin#44]
Django being in `install_requires` makes it hard for a project using `django_coverage_plugin` and `pip-compile` to specify their own version of Django.

**Comment by nedbat** [comment]
This library specifies "Django>=1.8". If your app specifies "Django==1.9.3", everything should be fine, or so I thought.  Can you show the details of how you are specifying Django, and what happens with pip-compile?

**Comment by beaugunderson** [comment]
OK, I think this is probably an issue limited to my specific setup, I split dev requirements out to a `dev-requirements.in`; because `django_coverage_plugin` adds a dependency on Django I end up with it in both my `requirements.txt` and my `dev-requirements.txt`. I'm thinking I can just combine both files since I install both sets of requirements anyway.

I still don't know how I feel about the dependency conceptually, but at least I've solved the issue at hand. :)

**Comment by merwok** [comment]
Same problem here.  I have a runtime.txt file (generated by pip-compile) with django, pysycopg2 and all run-time dependencies; my tests.txt file (generated too) only contains additional requirements like coverage, django-webtest, etc., without duplicating the django/etc dependencies.  In my tox config I run `pip-sync runtime.txt tests.txt` to install both sets of packages (pip-sync is equivalent to pip install -r but will also remove installed deps that are not in the requirement files).

If django ends up in both requirement files, pip-sync gives an error.

I think pip-tools is right here.  It’s straightforward and clear to have disjoint sets in requirement files, and not include base run-time deps in the test requirements.  Even before pip-tools existed, in the pyramid world extensions don’t depend on Pyramid, to give full control to the app assembler.

**Comment by PamelaM** [comment]
Thanks @merwok.  That's a well supported point.  
I think the plugin is depending on the setup.py `install_requires` to ensure that only supported versions of Django are installed.  One _could_ add a manual check to the plugin and run-time error if the Django version is unsupported.

**Comment by merwok** [comment]
Yes, that would work well with a tox config that documents the supported versions.

**Comment by merwok** [comment]
> If django ends up in both requirement files, pip-sync gives an error.

The behaviour is more subtle: an identical requirement may be present in runtime.txt and tests.txt, if it’s the same version (happens for six for instance).

I think the exact problem is that the *.in files are compiled separately, so pip-tools doesn’t have a chance to resolve the version constraints from django-coverage-plugin and my app.

**Comment by schinckel** [comment]
I think this one is resolved by PR #48 ?

**Comment by merwok** [comment]
Indeed

**Comment by beaugunderson** [comment]
👍
