### ISSUE TITLE
Activate TravisCI?

### ISSUE THREAD

**Issue by jambonrose** [nedbat/django_coverage_plugin#55]
Hi,
I note that there's a `.travis.yml` in the repo, but navigating to [TravisCI](https://travis-ci.org/nedbat/django_coverage_plugin) informs me that 'This is not an active repository.'

@nedbat : would you like to use Travis, and if so, would you mind activating it? Happy to help in any way I can.

**Comment by nedbat** [comment]
I activated it for my Travis account, I think?

**Comment by nedbat** [comment]
I'll admit to being confused about the difference between webhooks and integrations, travis-ci.org and travis-ci.com, etc.

Will this work?  https://travis-ci.org/nedbat/django_coverage_plugin

**Comment by jambonrose** [comment]
That sure looks like it works to me!

I get the impression Travis is consolidating .com and .org, but that's it's taking a ton of work. I expect everything to move to the new Github integration, but it doesn't work for OSS yet.

I'm closing the issue, as I think we're good to go, but I'll re-open it if tests don't run on PRs.

Thanks Ned!
