### ISSUE TITLE
Suport PyCharm Coverage

### ISSUE THREAD

**Issue by Atterratio** [nedbat/django_coverage_plugin#58]
If I run django tests with coverage from PyCharm, then geting error: "Coverage.py warning: Plugin file tracers (django_coverage_plugin.DjangoTemplatePlugin) aren't supported with PyTracer".

Any chance on support in future, or may be I can configure something to get worked this?

**Comment by jambonrose** [comment]
Hi @Atterratio ,

Could you share more information? What version of Coverage, Python, etc?

I'm afraid I don't have PyCharm, and googling "PyTracer" gives me results for a google project, raytracers, and a debugging tool that hasn't been updated in two years. If you could point me towards documentation, I'll be able to better understand the problem. The scope of the problem will help determine what a viable solution is (quick fix, PR welcome, or wont-fix).

**Comment by nedbat** [comment]
Coverage.py has two different implementations of the core trace function that collects data.  One is in C, called CTracer, the other in Python, called PyTracer.  If you are using PyTracer, it probably means that you are on a platform without a C compiler, or without the Python development dependencies.

@Atterratio Can you show us the output of "coverage debug sys,config" ?  Thanks.

**Comment by Atterratio** [comment]
@nedbat thanks, I'm unchecked "Use bundled coverage.py" option in PyCharm configuration and error message gone. 
But coverage for templates not show. I think I should go to PyCharm support for solve this problem.
Thanks all.
