### ISSUE TITLE
Configure template file extensions

### ISSUE THREAD

**Issue by jambonrose** [nedbat/django_coverage_plugin#60]
During conversation of #4, several people expressed the desire to report missing templates that do not end in `.html` or `.htm`, as some templates end in `.txt` or arbitrary extensions like `.subject`.

We should probably default to `.html`, `.htm`, and `.txt` (this last is used by Django emails). It should be possible for developers to configure the extensions being matched by the `find_executable_files()` method, so that they can add arbitrary extensions like `.subject` if necessary.

**Comment by alexandervlpl** [comment]
Great work on this plugin! In my project, the Django template engine is also used to generate PDFs. These templates are LaTeX files with `.tex` extensions. Seeing them in coverage reports would make this even *more* awesome.

**Comment by nedbat** [comment]
This is implemented in 07970d93a1a0af9cb3621e3e698faf8b3ee58986
