### ISSUE TITLE
Errors out with "branch = True"

### ISSUE THREAD

**Issue by jessamynsmith** [nedbat/django_coverage_plugin#7]
All my templates are erroring out as follows:
```eggtimer/templates/base.html   AttributeError: 'FileReporter' object has no attribute 'no_branch_lines'```

My .coveragerc is as follows:
```[run]
source = eggtimer
branch = True
omit = *tests*
    */migrations/*
    *__init__.py*
    *settings*
plugins =
    django_coverage_plugin
```
When I remove "branch=True" the error goes away.

**Comment by nedbat** [comment]
Fixed in #8
