### ISSUE TITLE
Report 0% on all templates not covered?

### ISSUE THREAD

**Issue by erdseb** [nedbat/django_coverage_plugin#71]
Hi!

Thanks for making this plug-in and sharing it with the community as software libre! :+1: 
I noticed that right now only the templates that are actually touched by existing tests make it into the report, i.e. if no tests gets template X loaded, it will not appear with 0% in the report and hence the resulting picture is more optimistic than reality. Is there a way to get all templates of first party Django apps into the report?

Thanks and best

Sebastian

**Comment by erdseb** [comment]
Any thoughts?

**Comment by erdseb** [comment]
@nedbat do you have a minute?

**Comment by nedbat** [comment]
@erdseb I have not been doing work on this plugin recently, or for some time actually.  I think this plugin should be finding unused templates.  A quick look at the code suggests that only .htm or .html files are considered.  Do you have differently named files?

Or, can you share a reproducible scenario with us?

**Comment by erdseb** [comment]
Hi Ned, thanks for your reply!
I will try to create a minimal reproducible example, deal :+1:

**Comment by erdseb** [comment]
> Or, can you share a reproducible scenario with us?

@nedbat yes! Please have a look at https://github.com/erdseb/django_coverage_plugin_issue_71_demo

**Comment by erdseb** [comment]
Any thoughts?

**Comment by erdseb** [comment]
@nedbat Please have a look at https://github.com/erdseb/django_coverage_plugin_issue_71_demo — I made it because you asked for it. Thank you!

**Comment by nedbat** [comment]
Thanks for the reproducible case.  And sorry it took so long.  And extra sorry that the answer is really simple, and I should have thought of it earlier.  You need to use the `--source=.` option (or some other `--source`) on the `coverage run` command for it to search for unexecuted files.  Once I do that with your example, both templates appear in the results.

I hope that helps.

**Comment by nedbat** [comment]
The already-imported warnings are now fixed in https://github.com/nedbat/coveragepy/issues/1150
