### ISSUE TITLE
plugin not working with pytest

### ISSUE THREAD

**Issue by jnoortheen** [nedbat/django_coverage_plugin#73]
Thanks for this great plugin. Now we don't have to worry about missing logic inside templates. I am not able to get it working with `pytest`. 
I execute the tests like this

![image](https://user-images.githubusercontent.com/6702219/83617381-9ae3dc80-a5a6-11ea-82aa-45c6652c705d.png)

But the report always show 0% coverage for all the templates in the project. 
![image](https://user-images.githubusercontent.com/6702219/83617466-be0e8c00-a5a6-11ea-9efb-e52b65ca4519.png)

has anyone used this plugin with pytest runner? am I missing something?

**Comment by thommor** [comment]
I'm currently trying to use this plugin with pytest and running into alot of issues.

If I run pytest without any tests that use templates then it works as expected and shows 0% coverage for all my templates.

However if I run tests the check the template was used it throws internal errors in coverage which causes no coverage to be generated at all even though all the tests still pass

```
users/tests/test_ui/test_login.py::LoginTestCase::test_login_template_used 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/---/venvs/TKfCJ_-O-py3.7/lib/python3.7/site-packages/_pytest/main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/---/venvs/TKfCJ_-O-py3.7/lib/python3.7/site-packages/_pytest/main.py", line 247, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/---/venvs/TKfCJ_-O-py3.7/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/---/venvs/TKfCJ_-O-py3.7/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/---/venvs/TKfCJ_-O-py3.7/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/---/venvs/TKfCJ_-O-py3.7/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/Users/---/venvs/TKfCJ_-O-py3.7/lib/python3.7/site-packages/pytest_cov/plugin.py", line 264, in pytest_runtestloop
INTERNALERROR>     self.cov_controller.finish()
INTERNALERROR>   File "/Users/---/venvs/TKfCJ_-O-py3.7/lib/python3.7/site-packages/pytest_cov/engine.py", line 46, in ensure_topdir_wrapper
INTERNALERROR>     return meth(self, *args, **kwargs)
INTERNALERROR>   File "/Users/---/venvs/TKfCJ_-O-py3.7/lib/python3.7/site-packages/pytest_cov/engine.py", line 231, in finish
INTERNALERROR>     self.cov.stop()
INTERNALERROR>   File "/Users/---/venvs/TKfCJ_-O-py3.7/lib/python3.7/site-packages/coverage/control.py", line 649, in save
INTERNALERROR>     data = self.get_data()
INTERNALERROR>   File "/Users/---/venvs/TKfCJ_-O-py3.7/lib/python3.7/site-packages/coverage/control.py", line 703, in get_data
INTERNALERROR>     if self._collector and self._collector.flush_data():
INTERNALERROR>   File "/Users/---/venvs/TKfCJ_-O-py3.7/lib/python3.7/site-packages/coverage/collector.py", line 426, in flush_data
INTERNALERROR>     self.covdata.add_file_tracers(self.mapped_file_dict(self.file_tracers))
INTERNALERROR>   File "/Users/---/venvs/TKfCJ_-O-py3.7/lib/python3.7/site-packages/coverage/sqldata.py", line 516, in add_file_tracers
INTERNALERROR>     "Can't add file tracer data for unmeasured file '%s'" % (filename,)
INTERNALERROR> coverage.misc.CoverageException: Can't add file tracer data for unmeasured file '/Users/---/git/---/templates/registration/login.html'
```

```
Coverage.py warning: Disabling plug-in 'django_coverage_plugin.DjangoTemplatePlugin' due to an exception:
Traceback (most recent call last):
  File "/Users/---/venvs/TKfCJ_-O-py3.7/lib/python3.7/site-packages/coverage/inorout.py", line 263, in should_trace
    file_tracer = plugin.file_tracer(canonical)
  File "/Users/---/venvs/TKfCJ_-O-py3.7/lib/python3.7/site-packages/django_coverage_plugin/plugin.py", line 179, in file_tracer
    self.debug_checked = check_debug()
  File "/Users/---/venvs/TKfCJ_-O-py3.7/lib/python3.7/site-packages/django_coverage_plugin/plugin.py", line 86, in check_debug
    "Template debugging must be enabled in settings."
django_coverage_plugin.plugin.DjangoTemplatePluginException: Template debugging must be enabled in settings.
```

**Comment by mschoettle** [comment]
@jnoortheen: Can you check whether your Django `DEBUG` setting is set to `True`? Mine accidentally was set to `False`. With debug enabled it works as expected.

**Comment by jnoortheen** [comment]
@mschoettle I think that is my case too. The tests are always ran with DEBUG=False. 

I haven't checked with `DEBUG=True `

**Comment by sparrowt** [comment]
I had the same issue using pytest (0% coverage reported for everything) and setting Django `DEBUG = True` did work ✔ (after also adding [`django_debug_mode = true`](https://pytest-django.readthedocs.io/en/latest/usage.html#django-debug-mode-change-how-debug-is-set)/`keep` to pytest.ini)

However I was under the impression that running tests with `DEBUG = True` is not best practice - is that a deliberate requirement of this plugin, or is it a bug that this plugin doesn't work with `DEBUG = False`?

**Comment by sparrowt** [comment]
The real issue here (I think) is that `check_debug` never gets past [`if not settings.configured:`](https://github.com/nedbat/django_coverage_plugin/blob/v1.8.0/django_coverage_plugin/plugin.py#L61) when running under pytest (having attached a debugger), so it never gets as far as the code which _should_ raise an exception saying _"Template debugging must be enabled in settings"_.

Perhaps the note which #30 added to the "Changes" section of README.rst
> Only the ``django.template.backends.django.DjangoTemplates`` template engine is
supported, and it must be configured with ``['OPTIONS']['debug'] = True``.

should be included in the main README, given that this is now archived away in HISTORY.rst so there is no mention of the template debugging requirement in the readme?

**Comment by jnoortheen** [comment]
there is this PR https://github.com/nedbat/django_coverage_plugin/pull/72/

**Comment by nedbat** [comment]
I can definitely add the note to the README.  But I'd also be interested in making the warning visible in pytest.  Can you give me a small project that demonstrates the problem?

**Comment by nedbat** [comment]
The README is updated in 3b7972fd4087612f26894e564ee902e951392c24, and coverage.py will also now show the warning when running under pytest (as of https://github.com/nedbat/coveragepy/commit/30c023b5b74f9c798645cbb3f35362ae046a4c25).
