### ISSUE TITLE
Defaults for template_extensions override .coveragerc "omit"

### ISSUE THREAD

**Issue by katylava** [nedbat/django_coverage_plugin#79]
We have "*.txt" in our .coveragerc "omit" section, but .txt files are still being included in coverage reports. Started when the `template_extensions` configuration option was added. We aren't using that configuration option, so it looks like the default values for it ignore "omit" in .coveragerc. I'd expect custom values to override it, but not the defaults.

**Comment by katylava** [comment]
Or if that's supposed to be the new behavior then the docs should make it clear.

> The Django template plugin uses some existing settings from your .coveragerc file. The source=, include=, and omit= options control what template files are included in the report.

**Comment by nedbat** [comment]
No, you are right, it should not be doing that.  Is there any chance you could give me a repo to try it with?

**Comment by katylava** [comment]
The repo we are using it in is private but I can make a simple version sometime this week.

**Comment by katylava** [comment]
Oops, sorry. Looks like we are overriding our base .coveragerc in a few of our repos, and those **do not** have `*.txt` in the `omit` section. So I think everything is working correctly.
