### ISSUE TITLE
Can't add file tracer data for unmeasured file 'templates/account/messages/logged_in.txt'

### ISSUE THREAD

**Issue by andre19rodrigues** [nedbat/django_coverage_plugin#84]
I use this _'templates/account/messages/logged_in.txt'_ file to override django-allauth messages. This is an empty file.
After upgrading coverage from version 4.5.4 to version 6.2 I'm getting this error:

```
Generating XML reports...
Destroying test database for alias 'default'...
Can't add file tracer data for unmeasured file '.../templates/account/messages/logged_in.txt'
```

The error doesn't show up if I remove `django_coverage_plugin` from .coveragerc file.

**Comment by nedbat** [comment]
Is your code public? Can you give me steps to reproduce the problem? Or a smaller example that shows it?

**Comment by andre19rodrigues** [comment]
Hi @nedbat, thanks for your reply and sorry I didn't get back to you sooner. Unfortunately, the code is private, and I can't reproduce the bug. Feel free to close this issue if you wish.

If it's relevant, I got rid of the error by editing the coverage file sqldata.py and adding `add=True` to `self._file_id(filename)`, in the `add_file_tracers()` function. However, I couldn't figure out why this particular file was not in the database at this point.

**Comment by andre19rodrigues** [comment]
I was unable to reproduce this error in a smaller test project. I'm omitting this file in the config for now.
