### ISSUE TITLE
Incorrect release shown in GitHub (2.0.1 vs 2.0.3)

### ISSUE THREAD

**Issue by jsolly** [nedbat/django_coverage_plugin#88]
### On Github
![image](https://user-images.githubusercontent.com/9572232/174419333-3cc8ba03-8b03-49ef-8cb7-9549be3dbd09.png)

### PyPI
![image](https://user-images.githubusercontent.com/9572232/174419339-7b6ab32d-3cf5-48d8-bed0-fd7c1f35f87e.png)

I like to watch repos to see when new releases are coming out. I think these two versions should match, right?

**Comment by nedbat** [comment]
They should, yes!  I've updated the releases on GitHub, thanks for the report.
